SHOW WAREHOUSES;

CREATE WAREHOUSE demo_werehouse
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Demo warehouse for learning purposes';

SHOW WAREHOUSES;

ALTER WAREHOUSE COMPUTE_WH
SET AUTO_SUSPEND = 60;

ALTER WAREHOUSE DEMO_WEREHOUSE
SET MAX_CLUSTER_COUNT = 3;

DROP WAREHOUSE DEMO_WEREHOUSE;

SHOW WAREHOUSES;    