USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS ifood;

CREATE SCHEMA IF NOT EXISTS ifood.staging; 

CREATE WAREHOUSE marketing_wh
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for development';

USE WAREHOUSE marketing_wh;

SHOW SCHEMAS IN DATABASE ifood;