USE ROLE USERADMIN;

CREATE ROLE ICE_CREAM_READER COMMENT = 'Able to read data from ice_cream_db';

CREATE ROLE ICE_CREAM_WRITER COMMENT = 'Able to do CRUD operations on ice_cream_db';
CREATE ROLE ICE_CREAM_ANALYST COMMENT = 'Able to view on data in ice_cream_db';

USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE dev_wh TO ROLE ICE_CREAM_READER;

GRANT USAGE ON DATABASE ice_cream_db TO ROLE ICE_CREAM_READER;

SHOW GRANTS TO ROLE ICE_CREAM_READER;

GRANT USAGE ON ALL SCHEMAS IN DATABASE ice_cream_db TO ROLE ICE_CREAM_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA ice_cream_db.public TO ROLE ICE_CREAM_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ice_cream_db.public TO ROLE ICE_CREAM_READER;

SHOW GRANTS TO ROLE ICE_CREAM_READER;

SHOW FUTURE GRANTS IN SCHEMA ice_cream_db.public;

GRANT ROLE ICE_CREAM_READER TO ROLE ICE_CREAM_WRITER;

SHOW GRANTS TO ROLE ICE_CREAM_WRITER;

GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ice_cream_db.public TO ROLE ICE_CREAM_WRITER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ice_cream_db.public TO ROLE ICE_CREAM_WRITER;

GRANT CREATE TABLE ON SCHEMA ice_cream_db.public TO ROLE ICE_CREAM_WRITER;

SHOW FUTURE GRANTS IN SCHEMA ice_cream_db.public;

USE ROLE ICE_CREAM_WRITER;

SELECT CURRENT_USER();

GRANT ROLE ICE_CREAM_WRITER TO USER DONNERSTEN;

USE ROLE ICE_CREAM_WRITER;


SHOW GRANTS TO USER DONNERSTEN;
SHOW GRANTS TO ROLE ICE_CREAM_READER;
SHOW GRANTS OF ROLE ICE_CREAM_READER;
